version: 0.2

env:
  variables:
    CI: "true"
    REPORT_DIR: "playwright-report-nightly"
  
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - apt-get update && apt-get install -y jq

      # Install Playwright browsers + system deps
      - echo "Installing Playwright browsers..."
      - npx playwright install chromium # install only chromium


  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - npx playwright --version
      - jq --version

  build:
    commands:
      - echo "Running Playwright tests..."
      - npx playwright test --project=chromium --workers=2

      # - npx playwright test --project=chromium --workers=2 --reporter=json --outputFile=playwright-results.json || true
      # - npx playwright test --project=chromium --workers=2 --reporter=html || true

  post_build:
    commands:
      - echo "Tests completed on $(date)"
      - echo "Extracting test results..."
      - echo "Webhook present? ${SLACK_WEBHOOK_URL_CODEBUILD:+YES}"
      - echo "SLACK_WEBHOOK_URL_CODEBUILD=$SLACK_WEBHOOK_URL_CODEBUILD"

      - |
        RESULT=$(node <<'EOF'
        const fs = require('fs');

        const report = JSON.parse(fs.readFileSync('playwright-results.json', 'utf8'));
        const stats = report.stats ?? {};

        const result = {
        PASSED: stats.expected ?? 0,
        FAILED: stats.unexpected ?? 0,
        SKIPPED: stats.skipped ?? 0
        };

        console.log(JSON.stringify(result));
        EOF
        )

        echo "RESULT=$RESULT"

        PASSED=$(echo "$RESULT" | jq -r .PASSED)
        FAILED=$(echo "$RESULT" | jq -r .FAILED)
        SKIPPED=$(echo "$RESULT" | jq -r .SKIPPED)

        echo "PASSED=$PASSED FAILED=$FAILED SKIPPED=$SKIPPED"


      - aws s3 cp playwright-report-nightly s3://playwright-reports-ra1/playwright-reports/$CODEBUILD_BUILD_ID/ --recursive

      - REPORT_URL="https://playwright-reports-ra1.s3.amazonaws.com/playwright-reports/$CODEBUILD_BUILD_ID/index.html"

      - |
        FAILED=${FAILED:-0}

        if [ "$FAILED" -gt 0 ]; then
        STATUS="❌ FAILED"
        else
        STATUS="✅ PASSED"
        fi

        echo "STATUS=$STATUS"

      - |
        PAYLOAD=$(cat <<EOF
        {
        "text": "🧪 Playwright Nightly Results\n\n$STATUS\n\nPassed: $PASSED\nFailed: $FAILED\nSkipped: $SKIPPED\n\nReport: $REPORT_URL"
        }
        EOF
        )

        echo "Sending to Slack..."

        curl -v -X POST \
          -H "Content-type: application/json" \
          --data "$PAYLOAD" \
          "$SLACK_WEBHOOK_URL_CODEBUILD"

artifacts:
  files:
    - $REPORT_DIR/**/*
    - test-results/**/*
  discard-paths: no

# reports:
#   playwright-report:
#     files:
#       - '**/*'
#     base-directory: playwright-report